name: Windows PowerShell
on: [workflow_dispatch]

jobs:
  build:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Script
        run: .\assemble.ps1
        shell: powershell
      - uses: lhotari/action-upterm@v1
      - with:
          limit-access-to-actor: true 
          wait-timeout-minutes: 5 
